<?/*<script type="text/javascript">
IngameNavi.disclaimer = new PureFW.Container(document.body, 259, 169, 506, 324);
IngameNavi.disclaimer.set_bg_img('ui/backgrounds/notice/notice.png');
IngameNavi.disclaimer.set_z_index(189);
IngameNavi.disclaimer.add_content('<div class="UI_info_popup_text" id="info_popup_text">\
		<h3>Allgemeine Informationen:</h3>\
		<p>\
			Die aktuelle Version der Nutzungsbedingungen ersetzt die vorherigen. Die\
			Gausus GmbH behält sich das Recht vor, Änderungen dieser Bedingungen ohne\
			Vorankündigung zu jeder Zeit durchzuführen.\
		</p>\
		<p>\
			Solltest du mit den Nutzungsbedingungen nicht einverstanden sein, ist es\
			dir nicht gestattet (weiter) als Betatester zu agieren, und du musst dies\
			im Falle eines schon dir zur Verfügung gestellten Accounts als Betatester\
			der Gausus GmbH unverzüglich vie Email an info@gausus.com mitteilen.\
		</p>\
		<p>\
			Die Nutzungsbedingungen haben auch über deine Tätigkeit als Betatester\
			hinaus bestand.\
		</p>\
		<h3>Vertraulichkeitsvereinbarung</h3>\
		<p>\
			Als Betatester verpflichtest du dich, alle im Spiel direkt oder indirekt\
			zur Kenntnis gekommenen vertraulichen Informationen strikt vertraulich zu\
			behandeln.\
		</p>\
		<p>\
			Es ist dir untersagt Bildmaterial (Screenshots, Grafiken, Vidoes, oder\
			ähnliches) und die vorherige Genehmigung der Gausus GmbH zu\
			veröffentlichen, zu verwerten, zu verwenden oder Dritten zugänglich zu\
			machen.\
		</p>\
		<p>\
			Es ist dir gestattet deinen Status als Betatester bekannt zu geben und\
			dich mit anderen Betatestern oder nicht Betatestern über Antexx\
			auszutauschen, solange dies privat oder auf Kommunikationsmitteln der\
			Gausus GmbH stattfindet (z.B.: www.gausus.com) und es keinen Widerspruch\
			zu diesen Nutzungsbedingungen darstellt.\
		</p>\
		<p>\
			Eine kommerzielle Nutzung oder Veräußerung von Daten oder Informationen\
			über Antexx ist in allen Fällen untersagt und benötigt die schriftliche\
			Genehmigung der Gausus GmbH.\
		</p>\
		<h3>Informationen zum Testen</h3>\
		<p>\
			Dies ist eine erste Testphase der Grundfunktionalitäten. Grafiken und\
			Spielmenü werden sich bis zum Releasetermin noch deutlich ändern.\
			Sämtliche Fehler und sonstige Ungereimtheiten sollen mit Hilfe des\
			Fehlerprotokolls direkt an die Gausus GmbH. weitergeleitet werden.\
		</p>\
		<p>\
			Das Formular zur Berichterstattung findest du, wenn du das\
			Fragezeichen(?)-Icon in der oberen Leiste anklickst.\
			Wir sind dankbar für Anregungen und Kommentare aller Art.\
		</p>\
		<p>\
			Alle Accounts sind Eigentum der Gausus GmbH. und können jederzeit\
			zurückgesetzt werden.\
		</p>\
		<p>\
			Ein Zurücksetzen wird es während der Testphasen immer mal wieder\
			geben, da gerade der Start ein wichtiges Testkriterium darstellt.\
		</p>\
		<p>\
			Getestet sollen nicht nur die Funktionen, sondern auch das Balancing. Dauern\
			Forschungen zu lange, sind bestimmte Inselbewohner zu schwach oder zustark,\
			zu teuer oder zu billig, und wie sieht es bei Zelten und Hütten aus?\
		</p>\
		<p>\
			Zudem bitte auch alle Design-Fehler oder -Hässlichkeiten melden.\
		</p>\
		<p>\
			Rechtschreibfehler und schlechte Formulierungen sollen zu dem aktuellen\
			Zeitpunkt noch <strong>nicht</strong> gemeldet werden, da die Texte alle\
			noch überarbeitet werden.\
		</p>\
		<p>\
			Wir sind für alle kreativen Vorschläge dankbar und für jegliches Feedback.\
		</p>\
		<h3>Aktuelle Einschränkungen, die keine Bugs sind</h3>\
		<p>\
			Aktuell ist es nicht möglich, Hütten und Zelte abzureißen. Dadurch ist es\
			insbesondere unmöglich, das Haupthaus zu zerstören und somit kann kein Spieler\
			von einer Insel verdrängt werden. Ist ein Spieler komplett handlungsunfähig\
			und hat keine Möglichkeit mehr zu gewinnen, soll dieser Spieler bitte eine\
			E-Mail an p.kemmeter@gausus.com schicken - nicht, dass er sich dann langweilt :)\
		</p>\
		<p>\
			Und nun viel Spaß beim Testen.\
		</p>\
	</div>\
<center><button onclick="javascript: IngameNavi.disclaimer.destroy()" class="UI_button UI_button_single_big"> Ich habe alles gelesen </button></center>\
');
</script>
*/?>