<script type="text/javascript">
IngameNavi = new Object();

</script>
<? include('scroll_arrows.tmpl.inc') ?>

<? include('info_popup.tmpl.inc')?>

<? include('data/ingame_navi/top_buttons.inc') ?>

<? include('data/ingame_navi/map_visit_navi.inc') ?>

<? include('data/ingame_navi/overview.inc'); ?>

<? include('game_menu.tmpl.inc') ?>

<? include('data/ingame_navi/notes.inc')?>

<script type="text/javascript">
//MapVisitNavi.hide_navigation();
//UIButtons.bottom_container.hide();
</script>
<div id="UI_window_to_tribes_arrow"></div>


