<div style="background: url(../pix/ui/backgrounds/buy_klunker/failed_bg.jpg) top center no-repeat #F2F7FF; width: 100%; height: 100%; ">
	<div style="color: #333; padding: 10px; margin: auto; width:500px">

		<p style="text-align: center; margin-top:0">
			<strong><span style="font-size: 1.5em">
			<?= LNG_BUY_KLUNKER_FAILED ?>
			</span></strong>
		</p>
		<div style="text-align: center; padding-top: 320px;">
			<button onclick="javascript: window.close();"><?=
				LNG_BUY_KLUNKER_B_CLOSE_WINDOW ?></button>
		</div>
	</div>
</div>